name: Generate

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to generate data for'
        required: true
        default: 'snapshot'
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Git
        uses: fregante/setup-git-user@v1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: pip install mcgen

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Purge previous output
        run: |
          rm -r ./generated
          rm -r ./processed

      - name: Run mcgen
        run: python -m mcgen --version ${{github.event.inputs.version}} --rawpath ./temp/raw --outpath ./processed --log INFO --processors mcgen.processors.write_version_file mcgen.processors.convert_json_files mcgen.processors.simplify_blocks mcgen.processors.split_registries custom_processors.summarize_data custom_processors.create_all_tags_data_pack

      - name: Cleanup repo
        run: |
          cp -r ./temp/raw/generated ./generated
          cp ./processed/VERSION.txt .

      - name: Push tag
        run: |
          version=$(< VERSION.txt)

          git add .
          git commit -m $version
          git tag -a $version -m $version
          git push --follow-tags